---
version: '3'

services:
  db:
    image: postgres
    container_name: ntumods_db
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ntumods
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  ntumods:
    build: .
    container_name: ntumods
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ntumods
    ports:
      - "8000:8000"
    environment:
      - DBNAME=ntumods
      - DBUSERNAME=postgres
      - DBPASSWORD=password
      - DBHOST=db
    depends_on:
      - db
