# Generated by Django 4.1 on 2023-02-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "duration",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=2, null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="module", name="sub_code",),
        migrations.RemoveField(model_name="module", name="type",),
        migrations.RemoveField(model_name="module", name="year",),
        migrations.AddField(
            model_name="module",
            name="credits",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="grading",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="module_prereq",
            field=models.ManyToManyField(blank=True, to="course_module.module"),
        ),
        migrations.AlterField(
            model_name="module",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="course", unique_together={("code", "sub_code", "year", "type")},
        ),
        migrations.DeleteModel(name="PreReq",),
        migrations.AddField(
            model_name="module",
            name="exam",
            field=models.ManyToManyField(blank=True, to="course_module.exam"),
        ),
    ]
