# Generated by Django 4.1.6 on 2023-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0002_alter_course_code_alter_module_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
