# Generated by Django 4.0.4 on 2023-02-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0003_exam_semester_exam_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_prereq',
            field=models.ManyToManyField(blank=True, to='course_module.module'),
        ),
    ]
