# Generated by Django 4.1.6 on 2023-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0003_alter_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='sub_code',
        ),
        migrations.RemoveField(
            model_name='module',
            name='type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
        migrations.AddField(
            model_name='module',
            name='credits',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='grading',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
