# Generated by Django 4.1.6 on 2023-02-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0004_remove_module_sub_code_remove_module_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'sub_code')},
        ),
    ]
