# Generated by Django 4.1.6 on 2023-02-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0005_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'sub_code', 'year', 'type')},
        ),
    ]
