# Generated by Django 4.1 on 2023-02-25 13:55

from django.db import migrations, models
import django.db.models.deletion
import timeslot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_module", "0001_initial"),
        ("venue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.CharField(blank=True, max_length=10, null=True)),
                ("type", models.CharField(blank=True, max_length=10, null=True)),
                ("group", models.CharField(blank=True, max_length=10, null=True)),
                ("day", models.CharField(blank=True, max_length=4, null=True)),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "semester",
                    models.IntegerField(
                        default=1
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course_module.module",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue",
                        to="venue.venue",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Time Slots", },
        ),
    ]
