# Generated by Django 4.1.6 on 2023-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0002_alter_timeslot_time_end_alter_timeslot_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='index',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
