# Generated by Django 4.1.6 on 2023-02-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingstaff',
            old_name='name',
            new_name='title',
        ),
    ]
