# Generated by Django 4.1.6 on 2023-02-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_name_teachingstaff_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingstaff',
            old_name='school',
            new_name='tag',
        ),
    ]
