# Generated by Django 4.1.6 on 2023-02-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_school_teachingstaff_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyword',
            new_name='Interest',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='word',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teachingstaff',
            old_name='keywords',
            new_name='interests',
        ),
    ]
