# Generated by Django 4.1.6 on 2023-02-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_keyword_interest_rename_word_interest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingstaff',
            name='profile_pic',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teachingstaff',
            name='url',
            field=models.URLField(default='-'),
            preserve_default=False,
        ),
    ]
