# Generated by Django 4.1 on 2023-02-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("sub_code", models.CharField(blank=True, max_length=10, null=True)),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={"unique_together": {("code", "sub_code", "year", "type")},},
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "duration",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=2, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("grading", models.CharField(blank=True, max_length=20, null=True)),
                ("credits", models.FloatField(blank=True, null=True)),
                ("exam", models.ManyToManyField(blank=True, to="course_module.exam")),
                (
                    "module_prereq",
                    models.ManyToManyField(
                        blank=True, null=True, to="course_module.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course_module.course",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course_module.module",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Course Modules",
                "ordering": ["course", "module"],
                "unique_together": {("course", "module")},
            },
        ),
    ]
