# Generated by Django 4.1.6 on 2023-02-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0002_alter_exam_duration_alter_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
