# Generated by Django 4.1.5 on 2023-02-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0005_remove_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
